### ISSUE TITLE
How do I use the blueprint snippet?

### ISSUE THREAD

**Issue by brog-io** [stormyark/Obsidian-Vault#2]
It brings me to custom background when I click on it, the other snippets work fine when I install the fonts but not sure how to use this one.

**Comment by stormyark** [comment]
- Download this [snippet](https://github.com/stormyark/Obsidian-Vault/blob/main/.obsidian/snippets/notebook-backgrounds.css)
- Move the snippet to your snippets folder
- Activate the snippet

Inside your note set this as a property:
```
---
cssclasses:
  - page-blueprint
  - embed-blueprint
---
```
